
/**
 * @file src/tools/templates.ts
 * @description Dynamic template fetching from env.GITHUB_OWNER/env.TEMPLATES_REPO_NAME.
 * @owner AI-Builder
 */


import { getOctokit } from '@services/octokit/core';
import { decode } from '@utils/base64';
import { getGithubConfigs } from '@utils/github/configs';

export const INFRA_TYPES = [
        'python_script',
        'cloudflare_workers',
        'cloudflare_pages',
        'vercel',
        'google_cloud',
        'generic'
] as const;

export type InfraType = typeof INFRA_TYPES[number];

/**
 * Recursively fetches files from the template repository.
 * Replaces {{name}} and {{project_name}} placeholders in text files.
 * @param env Cloudflare Bindings
 * @param infra Infrastructure type (folder name in template repo)
 * @param projectName Name of the new project
 */
export async function fetchTemplateFiles(env: Env, infra: string, projectName: string): Promise<Record<string, string>> {
        const octokit = await getOctokit(env);
        const config = getGithubConfigs(env);
        const templateRepo = {
            owner: config.owner,
            repo: config.templateRepo
        };

        const files: Record<string, string> = {};
        const infraType = INFRA_TYPES.includes(infra as any) ? infra : 'generic';

        console.log(`[Templates] Fetching templates for ${infraType} from ${templateRepo.owner}/${templateRepo.repo}`);

        async function fetchDir(path: string) {
                try {
                        const { data } = await octokit.rest.repos.getContent({
                                owner: templateRepo.owner,
                                repo: templateRepo.repo,
                                path
                        });

                        if (Array.isArray(data)) {
                                for (const item of data) {
                                        if (item.type === 'file') {
                                                // Fetch file content
                                                const { data: fileData } = await octokit.rest.repos.getContent({
                                                        owner: templateRepo.owner,
                                                        repo: templateRepo.repo,
                                                        path: item.path
                                                });

                                                if ('content' in fileData) {
                                                        let content = decode(fileData.content);

                                                        // Template Replacement
                                                        content = content.replace(/{{name}}/g, projectName);
                                                        content = content.replace(/{{project_name}}/g, projectName);

                                                        // Store relative path (remove infra prefix)
                                                        // e.g. cloudflare_workers/src/index.ts -> src/index.ts
                                                        const relativePath = item.path.replace(new RegExp(`^${infraType}/`), '');
                                                        files[relativePath] = content;
                                                }
                                        } else if (item.type === 'dir') {
                                                // Recurse
                                                await fetchDir(item.path);
                                        }
                                }
                        }
                } catch (e: any) {
                        console.error(`[Templates] Error fetching ${path}:`, e.message);
                        // Fallback to generic if specific infra fails? Or just throw?
                        // For now, if we can't find the folder, we might return empty or error.
                        if (e.status === 404 && path === infraType) {
                                console.warn(`[Templates] Template folder '${infraType}' not found. Falling back to 'generic'.`);
                                if (infraType !== 'generic') {
                                        await fetchDir('generic');
                                }
                        }
                }
        }

        await fetchDir(infraType);

        // Ensure critical files exist if empty (fallback logic could go here)
        if (Object.keys(files).length === 0) {
                console.warn("[Templates] No files found. Generating basic fallback.");
                files['README.md'] = `# ${projectName}\n\nGenerated by AI-Builder (Fallback).`;
        }

        return files;
}
