import type { APIRoute } from "astro";
import { app } from "@/app";

/**
 * Astro to Hono API Bridge
 * 
 * Directs all frontend traffic striking `/api/*` downwards into the modular 
 * OpenAPI Hono backend structure. Handles static builds, Dev servers, and SSR parity.
 */
export const ALL: APIRoute = async ({ request, locals }) => {
  // Extract typed environment generated by Cloudflare
  const env = locals.runtime?.env;
  if (!env) {
    throw new Error("Missing Cloudflare runtime in Astro.");
  }

  // Construct context stub satisfying the OpenAPIHono internal ExecutionContext dependency 
  // ensuring execution of underlying Cloudflare capabilities (waitUntil, etc.) do not crash
  const ctx = locals.runtime?.ctx || { 
    waitUntil: () => {}, 
    passThroughOnException: () => {} 
  };
  
  // Forward raw Request to native Hono router
  // We call the named export `app` which maps the `/api` prefix internally
  return app.fetch(request, env, ctx);
};
